# This workflow build a postgres, run the tests and generate a coverage report.

name: Run Unit Test via ng test and Report Coverage

on:
  push:
    branches:
      - dev
      - 'feature/*'

jobs:
  tests-coverage:
    name: Test & Coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
          if [ -f package.json ]; then npm install ; fi
      - name: Generate tests
        run: |
          ng test --no-watch --no-progress --browsers=ChromeHeadless
      - name: Generate coverage
        run: |
          ng test --no-watch --no-progress --code-coverage --browsers=ChromeHeadless
